services:
  mentorme-app:
    container_name: mentorme-app
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:80" # External:Internal
    depends_on:
      - mentorme-postgres
    environment:
      - ConnectionStrings__DefaultConnection=Host=mentorme-postgres;Port=5432;Database=postgres;Username=postgres;Password=postgres

  mentorme-postgres:
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    container_name: mentorme-postgres
    image: "postgres:15.2-bullseye"
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5445:5432"
    volumes:
      - data-protection-keys:/root/.aspnet/DataProtection-Keys
      - mentorme-postgres-volume:/var/lib/postgresql/data

volumes:
  data-protection-keys:
  mentorme-postgres-volume:
    